[package]
name = "main"
version = "0.2.0"
edition = "2018"

[dependencies]
handler = { path = "../function" }
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }

[profile.release]
lto = true
opt-level = 3
